### ISSUE TITLE
Update "Our Team" section

### ISSUE THREAD

**Issue by halfb00t** [maddevsio/madops#8]
* Remove Aziz Sadykov
* Fix beard on Belek
* Add Dmitri Khalezin and Marat Bediev: make their photo with Vlada, put beards on their faces

PS all ops shoud wear a beard)))

**Comment by denisoed** [comment]
Added fixed
1. Removed Aziz Sadykov
2. Added beard on Belek
2. Added Dmitri Khalezin and Marat Bediev

**Comment by denisoed** [comment]
Removed the beard from Belek, Dmitry and Marat

**Comment by halfb00t** [comment]
thnx!
